### PR TITLE
Adding Configurable System Users

### PR DESCRIPTION
**Pull request by moogar0880**
Adds the ability to specify a user to run each service as.

Not sure how you feel about this change but I have a requirement to run the various NSQ services as other system users. Would be great if this could be merged in.

### CODE REVIEW

**Comment by elubow** [comment]
Can you add yourself as a contributor to the `README.md` file?

**Comment by elubow** [comment]
Also, please take the two SHA hashes with an identical commit message 03cc848f847fbeebf6f9f6cfe4450cf67f6be765 and 8d165369bb414d4adbf1ce5426f7d1d1c20ef710 and merge them together.  Otherwise this looks good to me.  Once those things are done, I'll merge this PR.

**Comment by moogar0880** [comment]
Merged those two commits and added myself to the contributors. Would you like me to update the CHANGELOG as well?

**Comment by elubow** [comment]
Yes. Totally spaced on the changelog. Please update that too.

**Comment by moogar0880** [comment]
Should be all set. Thanks!

**Comment by elubow** [comment]
Excellent.  This looks good to me. Thanks.

**Pull request merged**
